[features]
seeds = false
skip-lint = false
[programs.localnet]
ackee_wsos_final = "9ivFLTnYaieHotAB1J6na8LPNKcH2fUA1GmmbDBuifdA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/13G5U3AkmiiUUQkb9epMMvOUP7Z8zhkj"
wallet = "/home/mike/.config/solana/dev-phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

